name: Openwrt Build Bot
on:
  push:
    branches: main
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
    home:
      description: 'location'
      required: false
      default: 'The Octoverse'
jobs:
  buildimg:
    name: Build Openwrt Image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - PROFILE_TARGET: x86/64
          PROFILE_VERSION: openwrt-19.07
          CONFIG_BUILDINFO: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/config.buildinfo
          FEEDS_BUILDINFO: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/feeds.buildinfo
          MANIFEST_URL: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/openwrt-19.07.7-x86-64-generic.manifest
          PACKAGES: luci-ssl luci-app-ddns luci-app-upnp
          INCLUDE_FILES: true
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt install -y libev-dev libc-ares-dev libudns-dev libncurses-dev build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools rsync subversion swig time xsltproc zlib1g-dev
          sudo -E apt-get -y dist-upgrade
          sudo -E apt-get clean
      - name: Initiate OpenWRT git source
        env:
          PROFILE_VERSION: ${{ matrix.PROFILE_VERSION }}
        run: |
          git clone -b $PROFILE_VERSION https://git.openwrt.org/openwrt/openwrt.git
      - name: Sync addon package
        run: |
          pwd
          # Vlmcsd
          git clone -b master https://github.com/mchome/openwrt-vlmcsd openwrt/package/vlmcsd
          git clone -b master https://github.com/mchome/luci-app-vlmcsd openwrt/package/luci-app-vlmcsd
      - name: Initiate configuration file
        env:
          PROFILE_VERSION: ${{ matrix.PROFILE_VERSION }}
          CONFIG_BUILDINFO: ${{ matrix.CONFIG_BUILDINFO }}
          REMOVE_TAG: ${{ matrix.REMOVE_TAG }}
        run: |
          cd openwrt
          make distclean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          rm -f ./.config*
          wget $CONFIG_BUILDINFO -O ../.config
          cp ../.config ./.config
          #make defconfig
          #sed -i '/=yes/d' ../.config
          #cat ../.config >> ./.config
          cat >> ./.config <<EOF
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-ssl=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          #make defconfig
          cat ./.config
          make download -j8
          #find dl -size -1024c -exec ls -l {} \;
          #find dl -size -1024c -exec rm -f {} \;
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          echo "============================================="
          #make package/vlmcsd/compile V=s -j$(nproc)
          find ./ -name "*factory*"
          echo "============================================="
          find ./ -name "*sysupgrade*"
