name: Openwrt Build Bot
on:
  push:
    branches: main
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
    home:
      description: 'location'
      required: false
      default: 'The Octoverse'
jobs:
  buildimg:
    name: Build Openwrt Image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - PROFILE_TARGET: x86/64
          PROFILE_VERSION: openwrt-19.07
          CONFIG_BUILDINFO: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/config.buildinfo
          FEEDS_BUILDINFO: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/feeds.buildinfo
          IB_URL: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/openwrt-imagebuilder-19.07.7-x86-64.Linux-x86_64.tar.xz
          SDK_URL: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/openwrt-sdk-19.07.7-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
          MANIFEST_URL: https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/openwrt-19.07.7-x86-64-generic.manifest
          PACKAGES: luci-ssl luci-app-ddns luci-app-upnp
          INCLUDE_FILES: true
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo apt install -y libev-dev libc-ares-dev libudns-dev libncurses-dev
          sudo -E apt-get -y dist-update
          sudo -E apt-get clean
      - name: Initiate OpenWRT git source
        env:
          PROFILE_VERSION: ${{ matrix.PROFILE_VERSION }}
        run: |
          git clone -b $PROFILE_VERSION https://git.openwrt.org/openwrt/openwrt.git
